### Criar apontamento-hora
POST http://localhost:3002/apontamento-horas
Content-Type: application/json

{
  "tipo_apontamento": "hora extra",
  "horario_inicio": "2022-01-01 13:00:00",
  "horario_fim": "2022-01-01 15:00:00",
  "justificativa": "blá blá blá"
}

### Buscar todos as apontamento-horas
GET http://localhost:3002/apontamento-horas

### Buscar apontamento-hora por id
GET http://localhost:3002/apontamento-horas/1

### Atualizar apontamento-hora
PUT http://localhost:3002/apontamento-horas/1
Content-Type: application/json

{
  "tipo_apontamento": "hora extra",
  "horario_inicio": "",
  "horario_fim": "",
  "justificativa": "blá blá blá"
}

### Deletar apontamento-hora (Não apaga do banco, apenas inativa o apontamento da hora)
DELETE http://localhost:3002/apontamento-horas/1