### Criar centro de resultado
POST http://localhost:3002/centro-de-resultados
Content-Type: application/json

{
  "nome": "Projeto 333",
  "numero": "12",
  "colaboradorId": 1,
  "gestorId": 1,
  "projetoId": 1
}

### Buscar todos os centro de resultados
GET http://localhost:3002/centro-de-resultados

### Buscar centro de resultado por id
GET http://localhost:3002/centro-de-resultados/1

### Atualizar centro de resultado
PUT http://localhost:3002/centro-de-resultados/1
Content-Type: application/json

{
  "nome": "Projeto 333",
  "numero": "15"
}

### Deletar centro de resultado (Não apaga do banco, apenas inativa o centro de resultados)
DELETE http://localhost:3002/centro-de-resultados/1