### Criar colaborador
POST http://localhost:3002/colaboradores
Content-Type: application/json

{
  "nome": "Maria",
  "matricula": "111111111",
  "tipo": true
}

### Buscar todos os colaboradores
GET http://localhost:3002/colaboradores

### Buscar colaborador por id
GET http://localhost:3002/colaboradores/1

### Atualizar colaborador
PUT http://localhost:3002/colaboradores/1
Content-Type: application/json

{
  "nome": "Maria",
  "matricula": "222222222",
  "tipo": "true"
}

### Deletar colaboradores (Não apaga do banco, apenas inativa o colaborador)
DELETE http://localhost:3002/colaboradores/1