### Criar hora extra
POST http://localhost:3002/horas-extras
Content-Type: application/json

{
  "nome_completo": "Fulano Beltrano",
  "matricula": 123,
  "entrada_1": "2022-01-01",
  "saida_1": "2022-01-01",
  "entrada_2": "2022-01-01",
  "saida_2": "2022-01-01",
  "nome_gestor": "Ciclano da Silva",
  "justificativa": "Teste"
}

### Buscar todos as horas extras
GET http://localhost:3002/horas-extras

### Buscar hora extra por id
GET http://localhost:3002/horas-extras/1

### Atualizar hora extra
PUT http://localhost:3002/horas-extras/1
Content-Type: application/json

{
  "nome_completo": "Fulano Beltrano",
  "matricula": 321,
  "entrada_1": "2022-01-01",
  "saida_1": "2022-01-01",
  "entrada_2": "2022-01-01",
  "saida_2": "2022-01-01",
  "nome_gestor": "Ciclano da Silva",
  "justificativa": "Testado"
}

### Deletar hora extra (Não apaga do banco, apenas inativa o usuário)
DELETE http://localhost:3002/horas-extras/1