### Criar projeto
POST http://localhost:3002/projetos
Content-Type: application/json

{
  "nome": "proejto 44",
  "numero_projeto": 18,
  "clienteId": 1
}

### Buscar todos os projetos
GET http://localhost:3002/projetos

### Buscar projeto por id
GET http://localhost:3002/projetos/1

### Atualizar projeto
PUT http://localhost:3002/projetos/1
Content-Type: application/json

{
  "nome": "proejto 44",
  "numero_projeto": "18"
}

### Deletar projetos (Não apaga do banco, apenas inativa o projeto)
DELETE http://localhost:3002/projetos/1