### Criar sobreaviso
POST http://localhost:3002/sobreavisos
Content-Type: application/json

{
  "nome_completo": "Fulano Beltrano",
  "matricula": 123,
  "entrada_1": "2022-01-01",
  "saida_1": "2022-01-01",
  "entrada_2": "2022-01-01",
  "saida_2": "2022-01-01",
  "nome_gestor": "Ciclano da Silva",
  "justificativa": "Teste"
}

### Buscar todos as sobreavisos
GET http://localhost:3002/sobreavisos

### Buscar sobreaviso por id
GET http://localhost:3002/sobreavisos/1

### Atualizar sobreaviso
PUT http://localhost:3002/sobreavisos/1
Content-Type: application/json

{
  "nome_completo": "Fulano Beltrano",
  "matricula": 321,
  "entrada_1": "2022-01-01",
  "saida_1": "2022-01-01",
  "entrada_2": "2022-01-01",
  "saida_2": "2022-01-01",
  "nome_gestor": "Ciclano da Silva",
  "justificativa": "Testado"
}

### Deletar sobreaviso (Não apaga do banco, apenas inativa o usuário)
DELETE http://localhost:3002/sobreavisos/1