### Criar usuario
POST http://localhost:3002/usuarios
Content-Type: application/json

{
  "role": "administrador",
  "email": "maria@email.com",
  "senha":"123456"
}

### Buscar todos os usuarios
GET http://localhost:3002/usuarios

### Buscar usuario por id
GET http://localhost:3002/usuarios/1

### Atualizar usuario
PUT http://localhost:3002/usuarios/1
Content-Type: application/json

{
  "role": "administrador",
  "email": "maria@email.com",
  "senha":"654321"
}

### Deletar usuarios (Não apaga do banco, apenas inativa o usuário)
DELETE http://localhost:3002/usuarios/1