### Criar verba
POST http://localhost:3002/verbas
Content-Type: application/json

{
  "codigo": "teste",
  "fator": 111,
  "descricao_verba": "sei lá"
}

### Buscar todos as verbas
GET http://localhost:3002/verbas

### Buscar verba por id
GET http://localhost:3002/verbas/1

### Atualizar verba
PUT http://localhost:3002/verbas/1
Content-Type: application/json

{
  "codigo": "3333",
  "fator": 111,
  "descricao_verba": "sei lá"
}

### Deletar verba (Não apaga do banco, apenas inativa a verba)
DELETE http://localhost:3002/verbas/1